name: Django Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: wms_db
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports: ['5432:5432']
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    env:
      POSTGRES_DB: wms_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: db
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up Docker Compose
      run: |
        docker compose -f docker-compose.yaml up -d --build
    
    - name: Wait for DB to be ready
      run: |
        echo "Waiting for PostgreSQL..."
        docker compose exec db bash -c "until pg_isready -U \$POSTGRES_USER; do sleep 1; done"
      env:
        POSTGRES_USER: postgres  # Ensure this matches your .env or docker-compose config
    
    - name: Wait for PostgreSQL to be ready
      run: |
        until pg_isready -h localhost -p 5432 -U postgres; do
          echo "Waiting for postgres..."
          sleep 1
        done

    - name: Run migrations
      run: |
        docker compose exec web python manage.py migrate

    - name: Run pytest inside container
      run: |
        docker compose exec web pytest

    - name: Shut down
      if: always()
      run: |
        docker compose down -v